const CPU_ACTION = "CPU_ACTION";
const CPU_ACTION_SUCCESS = "CPU_ACTION_SUCCESS";
const CPU_ACTION_FAILURE = "CPU_ACTION_FAILURE";
export const CPU_ACTION_TYPES = {
    pending: CPU_ACTION,
    success: CPU_ACTION_SUCCESS,
    failure: CPU_ACTION_FAILURE
};

const FILTER_BRAND_ACTION = "FILTER_BRAND_ACTION";
const FILTER_BRAND_ACTION_SUCCESS = "FILTER_BRAND_ACTION_SUCCESS";
const FILTER_BRAND_ACTION_FAILURE = "FILTER_BRAND_ACTION_FAILURE";
export const FILTER_BRAND_ACTION_TYPES = {
    pending: FILTER_BRAND_ACTION,
    success: FILTER_BRAND_ACTION_SUCCESS,
    failure: FILTER_BRAND_ACTION_FAILURE
};

const FILTER_PRICE_ACTION = "FILTER_PRICE_ACTION";
const FILTER_PRICE_ACTION_SUCCESS = "FILTER_PRICE_ACTION_SUCCESS";
const FILTER_PRICE_ACTION_FAILURE = "FILTER_PRICE_ACTION_FAILURE";
export const FILTER_PRICE_ACTION_TYPES = {
    pending: FILTER_PRICE_ACTION,
    success: FILTER_PRICE_ACTION_SUCCESS,
    failure: FILTER_PRICE_ACTION_FAILURE
};


const SEARCH_ACTION = "SEARCH_ACTION";
const SEARCH_ACTION_SUCCESS = "SEARCH_ACTION_SUCCESS";
const SEARCH_ACTION_FAILURE = "SEARCH_ACTION_FAILURE";
export const SEARCH_ACTION_TYPES = {
    pending: SEARCH_ACTION,
    success: SEARCH_ACTION_SUCCESS,
    failure: SEARCH_ACTION_FAILURE
};