const FETCH_MOBO_ACTION = "FETCH_MOBO_ACTION";
const FETCH_MOBO_ACTION_SUCCESS = "FETCH_MOBO_ACTION_SUCCESS";
const FETCH_MOBO_ACTION_FAILURE = "FETCH_MOBO_ACTION_FAILURE";
export const FETCH_MOBO_ACTION_TYPES = {
    pending: FETCH_MOBO_ACTION,
    success: FETCH_MOBO_ACTION_SUCCESS,
    failure: FETCH_MOBO_ACTION_FAILURE
};

const FETCH_CPU_ACTION = "FETCH_CPU_ACTION";
const FETCH_CPU_ACTION_SUCCESS = "FETCH_CPU_ACTION_SUCCESS";
const FETCH_CPU_ACTION_FAILURE = "FETCH_CPU_ACTION_FAILURE";
export const FETCH_CPU_ACTION_TYPES = {
    pending: FETCH_CPU_ACTION,
    success: FETCH_CPU_ACTION_SUCCESS,
    failure: FETCH_CPU_ACTION_FAILURE
};
const FETCH_GPU_ACTION = "FETCH_GPU_ACTION";
const FETCH_GPU_ACTION_SUCCESS = "FETCH_GPU_ACTION_SUCCESS";
const FETCH_GPU_ACTION_FAILURE = "FETCH_GPU_ACTION_FAILURE";
export const FETCH_GPU_ACTION_TYPES = {
    pending: FETCH_GPU_ACTION,
    success: FETCH_GPU_ACTION_SUCCESS,
    failure: FETCH_GPU_ACTION_FAILURE
};
const FETCH_PS_ACTION = "FETCH_PS_ACTION";
const FETCH_PS_ACTION_SUCCESS = "FETCH_PS_ACTION_SUCCESS";
const FETCH_PS_ACTION_FAILURE = "FETCH_PS_ACTION_FAILURE";
export const FETCH_PS_ACTION_TYPES = {
    pending: FETCH_PS_ACTION,
    success: FETCH_PS_ACTION_SUCCESS,
    failure: FETCH_PS_ACTION_FAILURE
};
const FETCH_RAM_ACTION = "FETCH_RAM_ACTION";
const FETCH_RAM_ACTION_SUCCESS = "FETCH_RAM_ACTION_SUCCESS";
const FETCH_RAM_ACTION_FAILURE = "FETCH_RAM_ACTION_FAILURE";
export const FETCH_RAM_ACTION_TYPES = {
    pending: FETCH_RAM_ACTION,
    success: FETCH_RAM_ACTION_SUCCESS,
    failure: FETCH_RAM_ACTION_FAILURE
};
const FETCH_STORAGE_ACTION = "FETCH_STORAGE_ACTION";
const FETCH_STORAGE_ACTION_SUCCESS = "FETCH_STORAGE_ACTION_SUCCESS";
const FETCH_STORAGE_ACTION_FAILURE = "FETCH_STORAGE_ACTION_FAILURE";
export const FETCH_STORAGE_ACTION_TYPES = {
    pending: FETCH_STORAGE_ACTION,
    success: FETCH_STORAGE_ACTION_SUCCESS,
    failure: FETCH_STORAGE_ACTION_FAILURE
};
const FETCH_CASE_ACTION = "FETCH_CASE_ACTION";
const FETCH_CASE_ACTION_SUCCESS = "FETCH_CASE_ACTION_SUCCESS";
const FETCH_CASE_ACTION_FAILURE = "FETCH_CASE_ACTION_FAILURE";
export const FETCH_CASE_ACTION_TYPES = {
    pending: FETCH_CASE_ACTION,
    success: FETCH_CASE_ACTION_SUCCESS,
    failure: FETCH_CASE_ACTION_FAILURE
};

const FETCH_BRANDS_ACTION = "FETCH_BRANDS_ACTION";
const FETCH_BRANDS_ACTION_SUCCESS = "FETCH_BRANDS_ACTION_SUCCESS";
const FETCH_BRANDS_ACTION_FAILURE = "FETCH_BRANDS_ACTION_FAILURE";
export const FETCH_BRANDS_ACTION_TYPES = {
    pending: FETCH_BRANDS_ACTION,
    success: FETCH_BRANDS_ACTION_SUCCESS,
    failure: FETCH_BRANDS_ACTION_FAILURE
};

const FETCH_PRICES_ACTION = "FETCH_PRICES_ACTION";
const FETCH_PRICES_ACTION_SUCCESS = "FETCH_PRICES_ACTION_SUCCESS";
const FETCH_PRICES_ACTION_FAILURE = "FETCH_PRICES_ACTION_FAILURE";
export const FETCH_PRICES_ACTION_TYPES = {
    pending: FETCH_PRICES_ACTION,
    success: FETCH_PRICES_ACTION_SUCCESS,
    failure: FETCH_PRICES_ACTION_FAILURE
};

const FILTER_BRAND_ACTION_ADD = "FILTER_BRAND_ACTION_ADD";
const FILTER_BRAND_ACTION_REMOVE = "FILTER_BRAND_ACTION_REMOVE";
export const FILTER_BRAND_ACTION_TYPES = {
    add: FILTER_BRAND_ACTION_ADD,
    remove: FILTER_BRAND_ACTION_REMOVE,
};

const FILTER_PRICE_ACTION_CHANGE = "FILTER_PRICE_ACTION_CHANGE";
export const FILTER_PRICE_ACTION_TYPES = {
    change: FILTER_PRICE_ACTION_CHANGE
};


const SEARCH_ACTION_SUCCESS = "SEARCH_ACTION_CHANGE";
export const SEARCH_ACTION_TYPES = {
    change: SEARCH_ACTION_SUCCESS
};
