const CPU_ACTION = "CPU_ACTION";
const CPU_ACTION_SUCCESS = "CPU_ACTION_SUCCESS";
const CPU_ACTION_FAILURE = "CPU_ACTION_FAILURE";
const MOBO_ACTION = "MOBO_ACTION";
const MOBO_ACTION_SUCCESS = "MOBO_ACTION_SUCCESS";
const MOBO_ACTION_FAILURE = "MOBO_ACTION_FAILURE";
export const CPU_ACTION_TYPES = {
    pending: CPU_ACTION,
    success: CPU_ACTION_SUCCESS,
    failure: CPU_ACTION_FAILURE
};
export const MOBO_ACTION_TYPES = {
    pending: MOBO_ACTION,
    success: MOBO_ACTION_SUCCESS,
    failure: MOBO_ACTION_FAILURE
};
